export const url = {
  authClient: '/',
  regClient: '/registration',
  server: 'http://35.176.167.155:8089',
  registration: '/registration/reg',
  auth: '/authorization/auth',
  signUp: '/signup',
  main: '/main',
  updateRoom: '/updateRoom',
  getBotStep: '/get-bot-step',
  joinRoom: '/joinRoom',
  getPossibleSteps: '/get-possible-steps',
  doStep: '/do-step',
  getStepOrder: '/get-step-order',
  ticTacToe: '/../../assets/img/Tic-tac-toe.png',
  Checkers: '/../../assets/img/Checkers.png',
};
