export const CLIENT = {
  authClient: '/',
  regClient: '/signup',
  ticTacClient: '/Tic-tac-toe',
  signUp: '/signup',
  main: '/main',
  statistic: '/statistic',
  'Tic-tac-toe': 'src/assets/img/Tic-tac-toe.png',
  Checkers: 'src/assets/img/Checkers.png',
  play: 'src/assets/img/play.png',
  bot: 'src/assets/img/ai.png',
  logo: 'src/assets/img/logout.svg',
  checkers: '/Checkers',
};

export const SERVER = {
  auth: '/authorization/auth',
  rooms: '/topic/rooms',
  game: '/topic/game',
  errors: '/user/topic/errors',
  doStep: '/radioactive/do-step',
  server: 'http://35.176.167.155:8089',
  socket: 'ws://35.176.167.155:8082',
  gameMenu: '/game-menu',
  joinRoom: '/radioactive/join-room',
  createRoom: '/radioactive/create-room',
  updateRoom: '/radioactive/update-room',
  getBotStep: '/radioactive/get-bot-step',
  topicBotStep: '/topic/bot',
  getStepOrder: '/radioactive/get-step-order',
  registration: '/registration/reg',
  getPossibleSteps: '/get-possible-steps',
};
